-- MySQL Script generated by MySQL Workbench
-- Tue Aug 18 10:54:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hoteismb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoteismb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoteismb` DEFAULT CHARACTER SET utf8 ;
USE `hoteismb` ;

-- -----------------------------------------------------
-- Table `hoteismb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteismb`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoteismb`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteismb`.`hotel` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoteismb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteismb`.`funcionarios` (
  `id_funcionarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `hotel_id_hotel` INT NOT NULL,
  PRIMARY KEY (`id_funcionarios`),
  INDEX `fk_funcionarios_hotel1_idx` (`hotel_id_hotel` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_hotel1`
    FOREIGN KEY (`hotel_id_hotel`)
    REFERENCES `hoteismb`.`hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoteismb`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteismb`.`quarto` (
  `id_quarto` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `andar` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `hotel_id_hotel` INT NOT NULL,
  PRIMARY KEY (`id_quarto`),
  INDEX `fk_quarto_hotel1_idx` (`hotel_id_hotel` ASC) VISIBLE,
  CONSTRAINT `fk_quarto_hotel1`
    FOREIGN KEY (`hotel_id_hotel`)
    REFERENCES `hoteismb`.`hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoteismb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteismb`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `data_reserva` DATE NULL,
  `entrada` DATE NULL,
  `saida` DATE NULL,
  `pagamento_id_pagamento` INT NOT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_usuarios1_idx` (`usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `hoteismb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoteismb`.`quarto_has_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteismb`.`quarto_has_reserva` (
  `quarto_id_quarto` INT NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  PRIMARY KEY (`quarto_id_quarto`, `reserva_id_reserva`),
  INDEX `fk_quarto_has_reserva_reserva1_idx` (`reserva_id_reserva` ASC) VISIBLE,
  INDEX `fk_quarto_has_reserva_quarto1_idx` (`quarto_id_quarto` ASC) VISIBLE,
  CONSTRAINT `fk_quarto_has_reserva_quarto1`
    FOREIGN KEY (`quarto_id_quarto`)
    REFERENCES `hoteismb`.`quarto` (`id_quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quarto_has_reserva_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `hoteismb`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
